import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")
const js = path.join(dir, "src/provider/models-snapshot.js")
const dts = path.join(dir, "src/provider/models-snapshot.d.ts")
const decl = `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const disabled = ["1", "true"].includes((process.env.OPENCODE_DISABLE_MODELS_FETCH ?? "").toLowerCase())

async function save(data: string) {
  await Bun.write(js, `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${data}\n`)
  await Bun.write(dts, decl)
}

const local = process.env.MODELS_DEV_API_JSON
const data = local
  ? await Bun.file(local).text()
  : disabled
    ? undefined
    : await fetch(`${modelsUrl}/api.json`)
        .then(async (res) => {
          if (!res.ok) throw new Error(`Failed to fetch ${modelsUrl}/api.json: ${res.status}`)
          return res.text()
        })
        .catch((err) => {
          console.warn(
            `Failed to refresh models snapshot from ${modelsUrl}: ${err instanceof Error ? err.message : String(err)}`,
          )
          return undefined
        })

if (data) {
  await save(data)
  console.log("Generated models-snapshot.js")
} else if (fs.existsSync(js)) {
  if (!fs.existsSync(dts)) await Bun.write(dts, decl)
  console.log("Using existing models-snapshot.js")
} else {
  await save("{}")
  console.warn("Generated empty models-snapshot.js")
}
